// Code generated by "stringer -type=AssetStatus"; DO NOT EDIT.

package assetloader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STAGED-0]
	_ = x[LOADED-1]
	_ = x[FAILED-2]
}

const _AssetStatus_name = "STAGEDLOADEDFAILED"

var _AssetStatus_index = [...]uint8{0, 6, 12, 18}

func (i AssetStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AssetStatus_index)-1 {
		return "AssetStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AssetStatus_name[_AssetStatus_index[idx]:_AssetStatus_index[idx+1]]
}
