// Code generated by "stringer -type=PlayerState"; DO NOT EDIT.

package player

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IDLE-0]
	_ = x[MOVING-1]
	_ = x[SLAMMING-2]
	_ = x[DYING-3]
	_ = x[LEAVING-4]
	_ = x[ENTERING-5]
}

const _PlayerState_name = "IDLEMOVINGSLAMMINGDYINGLEAVINGENTERING"

var _PlayerState_index = [...]uint8{0, 4, 10, 18, 23, 30, 38}

func (i PlayerState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PlayerState_index)-1 {
		return "PlayerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlayerState_name[_PlayerState_index[idx]:_PlayerState_index[idx+1]]
}
